### ISSUE TITLE
[Bug]: テンプレート機能を使用した際に動作するActionが最後に失敗する

### ISSUE THREAD

**Issue by Yamasaki-pan961** [yumemi-inc/flutter-mobile-project-template#157]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 現在の動作

期待する動作（不要なファイル削除やissue作成など）はすべて動作しているが、最後に以下のように表示されて失敗した扱いとなっている。
```
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/template-test/template-test/.github/actions/cleanup-copilot-settings'. Did you forget to run actions/checkout before running your local action?
``` 
https://github.com/Yamasaki-pan961/template-test/actions/runs/8109210309

### 期待される動作

ワークフローが成功するようになる

### 環境

```Markdown
- Commit Hash: c64550cae8916fdb145b83f5ec7d2626ec9123ad
```

**Comment by Kotaro666-dev** [comment]
@Yamasaki-pan961 
CC: @blendthink 

バグ起票ありがとうございます！
釜島も本バグを確認し、優先度高のタスクであることも認識したので、本チケットを釜島にアサインしてバグ修正対応を進行します！

**Comment by Kotaro666-dev** [comment]
# 調査メモ

以下の template-cleanup アクションに関連した cleanup が実行されているみたい。

https://github.com/yumemi-inc/flutter-mobile-project-template/blob/c761fb804492a901765d33330d23da16f0cde50f/.github/workflows/template-cleanup.yaml

ただし、`Post Cleanup Copilot Settings` に関係する step はワークフロー内で明示的に指示していない。そのため、GitHub Actions がデフォルト設定か何かで自動実行している可能性がある。

**Comment by Kotaro666-dev** [comment]
# 調査メモ

エラーメッセージを読み解く限り、 Composite Action 内の step で `actions/checkout` が実行されていないことを指摘されていそう。

```
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/template-test/template-test/.github/actions/cleanup-copilot-settings'. Did you forget to run actions/checkout before running your local action?
```

Node.js をセットアップする前に `actions/checkout` を実行する必要があるか？

```
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      # https://github.com/actions/setup-node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
```
