### ISSUE TITLE
多言語対応

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#3]
- 日本語と英語を対応して、日本語をデフォルトにする

```yaml:l10n.yaml
arb-dir: assets/l10n
output-dir: lib/gen/l10n
template-arb-file: app_ja.arb
output-localization-file: l10n.dart
output-class: L10n
synthetic-package: false
preferred-supported-locales:
  - ja
  - en
header: '// ignore_for_file: type=lint'
nullable-getter: false
```

- pubspec.yaml の `generate: true` の設定は削除する

FYI:
- https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
- https://qiita.com/blendthink/items/ca9fddf2b977400c6259

# このIssuesで対応しないこと

マルチパッケージ構成でも使いやすいようにする
