### ISSUE TITLE
[Improve]: GitHub Action の Dart 以外のフォーマッター整備

### ISSUE THREAD

**Issue by fa0311** [yumemi-inc/flutter-mobile-project-template#431]
### これに関する既存の Issue はありますか？

- [x] 既存の Issue はありませんでした

### 背景

GitHub Action の Dart 以外のフォーマッターを整備する

### 環境

```Markdown
...
```

**Comment by blendthink** [comment]
📝 
https://github.com/FlutterKaigi/2025/blob/main/.github/workflows/wc-check-style-dprint.yaml

**Comment by hidekitux** [comment]
FlutterKaigiを参考に利用するActionを更新して、`act -W '.github/workflows/wc-check-style-dprint.yaml' --container-architecture linux/amd64 -P ubuntu-24.04=catthehacker/ubuntu:act-latest`で動作確認済み

```yaml
name: Check dprint Style

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-style-dprint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.2.2
        with:
          install_args: "dprint"

      - name: Run style check
        run: dprint check
```
